name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push node 22
        uses: docker/build-push-action@v5
        with:
          context: ./22
          file: ./22/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:10.7.1-node-22
      - name: Build and push node 24
        uses: docker/build-push-action@v5
        with:
          context: ./24
          file: ./24/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:10.27.0-node-24
      - name: Build and push node 24 latest
        uses: docker/build-push-action@v5
        with:
          context: ./24
          file: ./24/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pnpm:latest